# Generated by Django 2.0.6 on 2020-05-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pic',
            field=models.ImageField(default='img/1.jpg', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='press',
            name='pic',
            field=models.ImageField(default='img/1.jpg', upload_to='img'),
        ),
    ]
