# Generated by Django 2.0.6 on 2020-05-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pic',
            field=models.ImageField(default='pic/1.jpg', upload_to='pic'),
        ),
    ]
